### ISSUE TITLE
A few issue

### ISSUE THREAD

**Issue by maxin9966** [mit-han-lab/nunchaku#11]
## envs:
ubuntu22
3090

### Issue 1:
Using hyper lora for acceleration does not seem to be working.

Here is the relevant code snippet:
pipeline.transformer.nunchaku_update_params('/home/models/loras/Hyper-FLUX.1-dev-8steps-lora.safetensors')
pipeline.transformer.nunchaku_set_lora_scale(0.125)

or

pipeline.load_lora_weights('/home/models/loras/Hyper-FLUX.1-dev-8steps-lora.safetensors')
pipeline.fuse_lora(lora_scale=0.125)

### Issue 2:
Both 1024x1024 and 768x1024 dimensions work without issues.
However, when using 800x1200, an error occurs:
python: /home/ma/work/nunchaku/src/pytorch_compat.h:8: void pytorch_compat::TORCH_CHECK(bool, const string&): Assertion `cond' failed.
Aborted (core dumped)

### Issue 3:
The following portion of your input was truncated due to CLIP's limitation in handling sequences up to 77 tokens: ['- realistic image that evokes a sense of unsettling beauty.']

### Issue 4:
To use the --use-qencoder parameter, you need to install deepcompressor.
Here are the steps:
git clone https://github.com/mit-han-lab/deepcompressor
poetry install, This installation process keeps encountering errors.

**Comment by maxin9966** [comment]
Additionally, there is another small question: 
Does the use of --use-qencoder result in a noticeable decline in image quality?

**Comment by lmxyy** [comment]
* Nunchaku's LoRA format is slightly different. We will provide a script to convert the diffusers LoRA to nunchaku LoRA.
* Currently, our engine only supports images with pixel counts that are multiples of 65,536, as in #9. You can try resolution 768*1280. We will fix this in our next release.
* I think this is the `diffusers` FLUX limit. You can check `diffusers` document to see if there is a way to bypass it.
* You can try commenting some dependencies in the `deepcompressor`. The complete installation instruction will be
```shell
git clone https://github.com/mit-han-lab/deepcompressor
cd deepcompressor
pip install poetry
```
Then delete Lines 12-17 in `pyproject.toml` and run
```shell
poetry install
```
We will release the dependencies of `deepcompressor` in the next release.
* The results may vary slightly due to the quantized text encoder, which alters the text embeddings. However, the overall generation capability remains the same, as the DiT model itself is unchanged.

**Comment by lmxyy** [comment]
Since there is no further replies in the issue, I will close it for now. Feel free to reopen it.
